### ISSUE TITLE
Don't show port in IDs when base.scheme and base.port are matched defaults

### ISSUE THREAD

**Issue by fractos** [dlcs/elucidate-server#3]
The IDs produced by Elucidate include the port numbers even if the ports are default for the base.scheme being used. Although this is mainly an aesthetic issue, it may cause problems in connected systems which use the ID as a flat key for hashing etc, since they wouldn't be expecting the port number to be included.

If base.scheme is "http" and base.port is 80,  or if base.scheme is "https" and base.port is 443, then it shouldn't show the port in the ID URI.

Example:
```
{
  "@context" : "http://www.w3.org/ns/anno.jsonld",
  "id" : "http://nlw-elucidate.digtest.co.uk:80/annotation/w3c/0099f7e4-46fd-4691-9858-fd5c8a2e025e/",
  "type" : "AnnotationCollection",
  "creator" : "http://example.com/publisher",
  "label" : "Steampunk Annotations",
  "first" : {
    "type" : "AnnotationPage",
    "as:items" : {
      "@list" : [ ]
    },
    "partOf" : "http://nlw-elucidate.digtest.co.uk:80/annotation/w3c/0099f7e4-46fd-4691-9858-fd5c8a2e025e/",
    "startIndex" : 0
  },
  "last" : "http://nlw-elucidate.digtest.co.uk:80/annotation/w3c/0099f7e4-46fd-4691-9858-fd5c8a2e025e/?page=0&desc=1",
  "total" : 0
}
```

**Comment by danielgrant** [comment]
It looks like this is the default behaviour of [org.apache.http.client.utils.URIBuilder](https://hc.apache.org/httpcomponents-client-4.5.x/httpclient/apidocs/org/apache/http/client/utils/URIBuilder.html), which is used for building up the base URI that is prefixed to all other IDs.

I will look into a fix for this.
