### ISSUE TITLE
Maintain versioned history of annotations

### ISSUE THREAD

**Issue by mattmcgrattan** [dlcs/elucidate-server#38]
Maintain an annotation history of particular annotations in a history table storing the jsonb.
'Exploded' tables (for fast retrieval by id, source, etc) will always be the latest version and are not versioned.

**Comment by danielgrant** [comment]
Version numbers will simply be incrementing integers, e.g. `1`, `2`, `3`, etc.

**Comment by danielgrant** [comment]
Implemented in [1.4.0](https://github.com/dlcs/elucidate-server/releases/tag/1.4.0).
