### ISSUE TITLE
Expose modified date for search

### ISSUE THREAD

**Issue by mattmcgrattan** [dlcs/elucidate-server#42]
Expose last modified date for querying:

The primary use case is to extract annotations created (or modified) since a given target date. With two primary motivations:
i) extraction of annotations to load into other systems (e.g. for data refinement, indexing in a bespoke search service, aggregation, etc), and
ii) extraction of annotations to then produce basic statistical information (e.g. number of annotations since $DATE, etc).

N.B. Elucidate cannot control what clients do with 'created'/'modified' information, so consistent results depend on consistent client behaviour.

**Comment by danielgrant** [comment]
Implemented in [1.4.0](https://github.com/dlcs/elucidate-server/releases/tag/1.4.0).
