### ISSUE TITLE
Search by text value in service "search by body" ?

### ISSUE THREAD

**Issue by nicolasfranck** [dlcs/elucidate-server#70]
I'm testing the search service, but I cannot figure out how it works:

https://github.com/dlcs/elucidate-server/blob/master/USAGE.md#search

I added this annotation:

https://adore.ugent.be/IIIF/manifests/archive.ugent.be%3AEE70B70C-0C11-11E6-9A91-1252F264C48D/canvases/DS.0_11/text-annotations/670

But I cannot find it using the "search by body" service, using these parameters:

* fields: source
* value: oorlog

Looking at the underlying postgres function, it looks like the parameter
is compared against sourceiri or bodyiri.

Am I looking in the wrong direction?

Thanks in advance

P.S. Is there a better place to ask questions, for github is mostly used for issues

**Comment by nicolasfranck** [comment]
I looked in the postgres table, and the columns bodyiri and sourceiri are empty

**Comment by danielgrant** [comment]
Hi @nicolasfranck,

The `/services/search/...` endpoints currently only search against the `id` field of a `body` or `target` object (if `fields=id` is provided in the query), or the `id` field of the inner `source` object of a `body` or `target` object (if `fields=source` is provided in the query).

There is currently no functionality in Elucidate that allows for example the searching of the free text field within a `source` block.

Regarding `bodyiri` and `sourceiri` being empty in the database, this will be the case if both no `id` values are provided in the `target` or `body` objects of a payload and no `id` values are provided in the `source` object contained within a `target` or `body` object. There is a small chance that the `elucidate-server.properties` is also not configured properly - the `listeners.registered` property must contain `com.digirati.elucidate.infrastructure.listener.AnnotationExtractorRegisteredListenerImpl` for this to work, as this is the class that is invoked after an annotation is created / modified, which breaks up the annotation into its constituent parts for querying.

Cheers,
Daniel.

**Comment by nicolasfranck** [comment]
Ok, so for now this module should only be used to collect all annotations for a specific container, rather than as a search service. E.g. use it in mirador to show the annotations and let the user edit them.

Maybe it is not really necessary to add such a feature. Better to use this as the safe backend store, and add a "document" to a search service like Solr or ElasticSearch. Full text search in a database is never a good choice, I think.

**Comment by tomcrane** [comment]
@nicolasfranck Elucidate provides the kind of basic search operations you might need when _managing_ annotations (and we can more operations of that nature, would be good to hear your opinions on it).

For implementing a IIIF Search API on top of those annotations, we have https://github.com/dlcs/the-mathmos-server

Mathmos will index annotations in Elucidate, but will also index full text derived from OCR and other sources, and present search results as annotations regardless of their original source. We're working on features and integration scenarios for Mathmos.

**Comment by nicolasfranck** [comment]
@tomcrane @danielgrant : Thanks for clearing this out ;-). Well for now I think it is better to keep Elucidate simple, and let ElasticSearch do the heavy stuff.

**Comment by nicolasfranck** [comment]
@tomcrane the indexer "pygar" has been removed from this repository. Is this functionality moved to another place? Or is it considered deprecated? I'm trying to figure out how to index the annotations in the-mathmos-server.
