### ISSUE TITLE
How to run elucidate-server in Windows?

### ISSUE THREAD

**Issue by tyy0402** [dlcs/elucidate-server#76]
I installed Java 8, Apache Tomcat 8 and PostgreSQL 9.5 on Windows. After using `mvn clean package install -U` to elucidate-parent, elucidate-common-lib and elucidate-converter, I don't know how to run elucidate-server. Can it run in windows? Should I open a port or a jar?

**Comment by danielgrant** [comment]
Hi @tyy0402,

Elucidate is delivered as a fairly standard Java web application.

Once you've built and made the various dependencies available to Maven, you can use Maven to build `elucidate-server` into a `.war` and simply drop it into your Java Servlet Container (i.e. Tomcat).

I will create an issue to expand out the installation instructions in the `README.md`.

**Comment by danielgrant** [comment]
Tracked in #77.
