### ISSUE TITLE
Annotations visible only to creator

### ISSUE THREAD

**Issue by tomcrane** [dlcs/elucidate-server#79]
From @workergnome:

> We would like to add a mechanism to Elucidate that allows access to annotations to be restricted to their only being seen by the user that has created them.  We would like this to extend out through all the various APIs by which one may access annotations through Elucidate.  We would like the mechanism for providing authentication to be a JWT.

**Comment by tomcrane** [comment]
@danielgrant says:

> [...] who is the authentication provider? Will they have an existing sign on service against which users will authenticate and be provided with a JSON Web Token? Or does Elucidate (or some other component provided alongside Elucidate) have to handle authentication? If this is the case, we’re getting into storing usernames, passwords, etc, which will add some complexity.

> We also need to consider how we store the creator of the annotation. A W3C compliant annotation already has a “creator” and “generator” field, but there’s currently nothing preventing a client from inserting anything they want into these fields. We could keep it like this, and store the actual
creator as metadata in the database? But I suspect they’ll want this information inserted into the “creator” field instead.

**Comment by tomcrane** [comment]
More discussion copied from Slack:

danielgrant [8:57 AM]
If we use JWT for authentication and embed tokens in the `Authorization` header, it shouldn't cause any issues with regards to breaking the specification. We've added additional headers in the past, e.g. for Memento to traverse annotation histories.

...

...Assuming [Getty provide the authentication server, I'm fairly sure we could do (2). I believe (1) already exists in some format in the `digirati-co-uk` repository, so it would just be a case of moving that to the `dlcs` organisation and tarting it up a bit.
(3) would be a stretch but doable. #81 [pushing it]
#81 would include a new set of API's and an associated web interface. It's a chunk of work.

**Comment by tomcrane** [comment]
garytierney [9:42 AM]
validating a JWT could be fairly trivial if they're taking a simple PKI approach (take a JWT, validate its signature against the providers public key), any sort of authentication server / OAuth style flow would be a bit more complicated I think

matt-mcg [9:59 AM]
So, the core use cases, to reiterate are going to be:

validating that the user is the creator of the annotation
validating that the user is a member of a group authorised to perform read/write/update operations on an annotation
can we do those using simple key based verification, and what would need to be available at their end to make that happen?

garytierney [10:03 AM]
the 2 approaches are computing a HMAC for the token with a symmetric key and validating that (assuming the server has the symmetric key), or signing the token with an asymmetric key pair (i.e. an RSA key pair, or certificate, the server validating the token would then validate against the public key or follow the trust chain of the cert)

garytierney [10:04 AM]
I'm not sure if Elucidate will be creating the token here, would need Getty to verify if they have an authentication server

...
garytierney [10:05 AM]
Elucidate wouldn't issue the JWT in that case
it'd just receive one

root [10:05 AM]
depends, it could be a passthrough

Im not saying this is the best idea, or even a good one, but in the way that winston accepts a username and password and authenticates it agains some store of credentials, if Getty have some sort of authentication server which _isn’t_ JWT, then we could authenticate against that, and if its successful issue a JWT

| ” We would like the mechanism for providing authentication to be a JWT.”
thats the key bit for the discussion above. Its like @garytierney says - If they just want the mechanism by which clients authenticate with elucidate to be JWT based, shouldn’t be hard. If they’ve a more complex environment, then its harder.  Without more detail we’d be best to assume (and state the assumption) that its the former. But it would be good if we could get more detail

**Comment by workergnome** [comment]
Hi--We're looking for the simpler of the solutions.  I would assume that the Getty would provide the authentication server, and would pass a JWT via the standard header to Elucidate.  Elucidate would (through a yet-unspecified manner) have a list of authorized users and would have access to the private key, and would verify the identity.   We're open to your advice via best-practices for how to provide that list, and how to have elucidate obtain the private key.

I would think that all of this would be managed at the application level, not at the Web Annotation level.  As you said, I don't think there's a mechanism for doing this via the standard, so storing these permissions within Elucidate would be fine by me.

**Comment by garyttierney** [comment]
Regarding:

> Elucidate would [..] have a list of authorized users

Would that be a list of users who are authorized to access any annotation, regardless of the creator (and potentially groups)?

**Comment by workergnome** [comment]
Reconsidering--I think that I was making this too complicated, thinking that we had to know ahead of time who would be authorized to create annotations.  Instead, it seems more useful that should assume that anyone who has a signed key is authorized to create annotations.

**Comment by workergnome** [comment]
I don't think we need a superuser class--though I could be convinced!

**Comment by danielgrant** [comment]
Hi @workergnome,

This should summarise the enhancement (this also covers #80):

* A third party authentication service will provide authentication to users, at which point they will be issued with a JWT.
* This JWT will be passed through to Elucidate using the standard `Authorization` header.
* Elucidate will have a copy of the key used to encrypt the JWT, and therefore will be able to decrypt and read the token.
* The presence of a valid, decryptable token in the `Authorization` header is evidence that the user is authorised to use Elucidate.
* The JWT will define what roles the user has. These will be limited to `admin` and `user`.
   * A user with `admin` access has the ability to view, update and delete all annotations at all times.
   * A user with `user` access has the ability to view, update and delete annotations they own, and view annotations they has visibility of by virtue of their group memberships (see #81).
- When a user creates an annotation, they are assigned "Owner" permission on that annotation.
- Users are assigned group membership through the users / group API (see #81).

**Comment by danielgrant** [comment]
Implemented in 1.5.0.
