### ISSUE TITLE
Annotations visible to groups

### ISSUE THREAD

**Issue by tomcrane** [dlcs/elucidate-server#80]
From @workergnome:

> We would like a way to provide access to annotations to one or more predefined groups of users.

**Comment by tomcrane** [comment]
@danielgrant says:

> This seems like a natural part of implementing #79 anyway.

**Comment by workergnome** [comment]
I could see attaching groups/roles to an annotation to be part of the creation of the annotation, and I could also see it being a second request once the annotation is created.  That's probably dependent on architecture and standards...both would serve my needs.

For our initial implementation, I would say that only creators (or admins?) have update/delete permission.  All others have only read permissions.  It would be useful to be eventually be able to allow for a more complex matrix of "I assign this user or this group this set of rights for this annotation", but I don't know that we know yet enough to know what those might be, or how to do that.  I would not be _upset_ if we had that, but that seems like a "next phase" sort of problem.

**Comment by danielgrant** [comment]
Implemented in 1.5.0.
