### ISSUE TITLE
Generated page URIs from temporal searches respond with 400 (Bad Request)

### ISSUE THREAD

**Issue by garyttierney** [dlcs/elucidate-server#86]
A temporal search for a date represented by an ISO-8001 timestamp (e.g. http://elucidate/annotation/w3c/services/search/temporal?since=2018-05-01T00:00:00.000Z&levels=annotation&types=created) returns valid results.  However, following any of the links to the next/prev/first/last pages will result in a 400 (Bad Request) response, likely because Elucidate is generating page URIs with the wrong date format:

http://elucidate/annotation/w3c/services/search/temporal?types=created&page=2&levels=annotation&since=Tue+May+01+00%3A00%3A00+UTC+2018&desc=1

**Comment by danielgrant** [comment]
Thanks @garyttierney.

The offending code exists in `IRIBuilderServiceImpl.java`: https://github.com/dlcs/elucidate-server/blob/master/elucidate-common-lib/src/main/java/com/digirati/elucidate/common/service/impl/IRIBuilderServiceImpl.java

Where `Date` objects are passed in, no attempt to format has been made when they're being converted to a String, so it's falling back to Java's default `.toString()` behaviour.

**Comment by danielgrant** [comment]
Fixed in 1.5.0.
